#!/usr/bin/env node
import fs from 'node:fs'
import path from 'node:path'
import process from 'node:process'
import { fileURLToPath } from 'node:url'
import { execFile } from 'node:child_process'
import { promisify } from 'node:util'
import { Deck } from './device.mjs'
import { ensureDirs,rootDir,statusDir,logFile,loadConfig,readAgents,attachWorkspaces,getTopology,Topology,buildScene,View,focusWorkspace,focusSurface,cmuxRun } from './core.mjs'
const exec=promisify(execFile),HERE=path.dirname(fileURLToPath(import.meta.url)),ROOT=path.dirname(HERE),LABEL='com.pideck.agent',PLIST=path.join(process.env.HOME,'Library/LaunchAgents',`${LABEL}.plist`)
function log(message){ensureDirs();fs.appendFileSync(logFile(),`${new Date().toISOString()} ${message}\n`)}
function xml(s){return String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&apos;')}
function packageVersion(){return JSON.parse(fs.readFileSync(path.join(ROOT,'package.json'),'utf8')).version}
function pidFile(){return path.join(rootDir(),'daemon.pid')}
function acquire(){ensureDirs();try{const old=Number(fs.readFileSync(pidFile(),'utf8'));if(old){try{process.kill(old,0);return false}catch{}}}catch{}fs.writeFileSync(pidFile(),String(process.pid),{mode:0o600});return true}
function release(){try{if(Number(fs.readFileSync(pidFile(),'utf8'))===process.pid)fs.unlinkSync(pidFile())}catch{}}
async function snapshot(topology=null){const t=topology||await getTopology(),agents=readAgents();return attachWorkspaces(t,agents,false)}
function payload(ws,now=Date.now()/1000){return{version:packageVersion(),workspaces:ws.map(w=>({id:w.id,title:w.title,selected:w.selected,state:w.state(now),needsYou:w.needsYou(now),agents:w.liveAgents(now).map(a=>({sessionId:a.sessionId,label:a.label,state:a.effectiveState(now),activity:a.activity,branch:a.branch,surfaceId:a.surfaceId,pid:a.pid,ageSeconds:Math.round(a.ageSeconds(now)),stuck:a.stuck(now),subagents:a.liveChildren(now).length}))}))}}
class Daemon {
  constructor(){this.config=loadConfig();this.view=new View();this.actions=[];this.deck=null;this.topology=null;this.topologyAt=0;this.topologyOkAt=0;this.failing=false;this.lastPress=0;this.stopped=false}
  async topologyNow(force=false){const now=Date.now()/1000;if(force||!this.topology||now-this.topologyAt>this.config.topology_interval){this.topologyAt=now;try{this.topology=await getTopology();this.topologyOkAt=now;if(this.failing)log('cmux topology recovered');this.failing=false}catch(e){if(!this.failing)log(`cmux topology unavailable: ${e.message}`);this.failing=true;if(!this.topology||now-this.topologyOkAt>this.config.topology_grace)this.topology=new Topology({})}}return this.topology}
  async workspaces(force=false){return attachWorkspaces(await this.topologyNow(force),readAgents(),!!this.config.only_with_agents)}
  async refresh(){if(this.view.mode==='agents'&&this.config.agents_view_timeout>0&&this.lastPress&&Date.now()/1000-this.lastPress>this.config.agents_view_timeout)this.view=new View();const [keys,v]=buildScene(await this.workspaces(),this.view,this.deck?.keyCount||6);this.view=v;this.actions=keys.map(k=>k.action);await this.deck?.setScene(keys.map(k=>k.spec))}
  async press(i,long){this.lastPress=Date.now()/1000;const a=this.actions[i];if(!a)return;try{if(a.type==='back')this.view=new View();else if(a.type==='page')this.view=this.view.withPage(a.page);else if(a.type==='focus_agent'){if(a.surfaceId)await focusSurface(a.surfaceId,a.workspaceId,a.windowId);else if(a.workspaceId)await focusWorkspace(a.workspaceId,a.windowId);this.view=new View()}else if(a.type==='drill'){if(long){await focusWorkspace(a.workspaceId,a.windowId);this.view=new View()}else{const w=(await this.workspaces()).find(x=>x.id===a.workspaceId),agents=w?.liveAgents().filter(x=>x.surfaceId)||[];if(!agents.length){await focusWorkspace(a.workspaceId,a.windowId);this.view=new View()}else if(agents.length===1&&this.config.focus_single_agent_directly){await focusSurface(agents[0].surfaceId,a.workspaceId,a.windowId);this.view=new View()}else this.view=new View('agents',a.workspaceId)}}}catch(e){log(`cmux action failed: ${e.message}`)}await this.refresh()}
  async run(){while(!this.stopped){try{this.deck=await new Deck((i,l)=>this.press(i,l)).open(this.config.brightness);log(`deck connected (${this.deck.keyCount} keys, serial ${await this.deck.serial()})`);this.deck.start();while(!this.stopped&&this.deck.deck){await this.refresh();await new Promise(r=>setTimeout(r,this.config.poll_interval*1000))}if(!this.stopped)log('deck disconnected, waiting to reconnect')}catch(e){log(`deck unavailable: ${e.message}`)}finally{await this.deck?.close();this.deck=null}if(!this.stopped)await new Promise(r=>setTimeout(r,this.config.reconnect_interval*1000))}}
  stop(){this.stopped=true}
}
async function run(){if(!acquire())return;const d=new Daemon();const stop=()=>{d.stop();release()};process.on('SIGTERM',stop);process.on('SIGINT',stop);try{await d.run()}finally{release()}}
async function setup(){ensureDirs();fs.mkdirSync(path.dirname(PLIST),{recursive:true});let password='';try{password=fs.readFileSync(path.join(rootDir(),'cmux-password'),'utf8')}catch{}const env=`<key>PI_DECK_HOME</key><string>${xml(rootDir())}</string>${password?`<key>CMUX_SOCKET_PASSWORD</key><string>${xml(password)}</string>`:''}`;const plist=`<?xml version="1.0" encoding="UTF-8"?>\n<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">\n<plist version="1.0"><dict><key>Label</key><string>${LABEL}</string><key>ProgramArguments</key><array><string>${xml(process.execPath)}</string><string>${xml(fileURLToPath(import.meta.url))}</string><string>run</string></array><key>WorkingDirectory</key><string>${xml(ROOT)}</string><key>EnvironmentVariables</key><dict>${env}</dict><key>RunAtLoad</key><true/><key>KeepAlive</key><true/><key>StandardErrorPath</key><string>${xml(path.join(rootDir(),'launchd.err.log'))}</string><key>StandardOutPath</key><string>${xml(path.join(rootDir(),'launchd.out.log'))}</string></dict></plist>\n`;fs.writeFileSync(PLIST,plist,{mode:0o600});try{await exec('launchctl',['unload',PLIST])}catch{}await exec('launchctl',['load',PLIST]);return `Installed and started pi-stream-deck ${packageVersion()} launchd service.`}
async function uninstall(){try{await exec('launchctl',['unload',PLIST])}catch{}try{fs.unlinkSync(PLIST)}catch{};try{const pid=Number(fs.readFileSync(pidFile(),'utf8'));if(pid)process.kill(pid,'SIGTERM')}catch{}return 'Stopped and removed the pi-stream-deck launchd service.'}
async function status(){let ws;try{ws=await snapshot()}catch{ws=attachWorkspaces(new Topology({}),readAgents(),false)}return JSON.stringify(payload(ws),null,2)}
async function doctor(){const devices=await Deck.devices();let cmux='ok';try{await cmuxRun(['ping'],2000)}catch(e){cmux=e.message}let running=false;try{process.kill(Number(fs.readFileSync(pidFile(),'utf8')),0);running=true}catch{}return `package  ${packageVersion()}\ndaemon   ${running?'ok':'not running'}\ndeck     ${devices.length?`ok (${devices[0].model})`:'not found'}\ncmux     ${cmux}\nagents   ${readAgents().length} reporting in ${statusDir()}`}
async function selftest(){const deck=await new Deck().open(70),demo=[{kind:'workspace',title:'Pi Agent',status:'waiting',dots:['working','waiting','idle'],count:3,age:'2m',selected:true},{kind:'workspace',title:'api',status:'working',dots:['working'],count:1,age:'now'},{kind:'agent',title:'review',subtitle:'⤷ 2 subagents',status:'working',subagents:2,age:'now'},{kind:'agent',title:'question',subtitle:'waiting for your answer',status:'question',age:'1m'},{kind:'agent',title:'tests',subtitle:'npm test',status:'compacting',age:'8s'},{kind:'back',title:'Pi Agent'}];await deck.setScene(demo);await new Promise(r=>setTimeout(r,8000));await deck.close();return 'Self-test complete.'}
const command=process.argv[2]||'run';try{if(command==='run')await run();else if(command==='setup')console.log(await setup());else if(command==='uninstall')console.log(await uninstall());else if(command==='status')console.log(await status());else if(command==='doctor')console.log(await doctor());else if(command==='selftest')console.log(await selftest());else{console.error('usage: daemon.mjs run|setup|uninstall|status|doctor|selftest');process.exitCode=2}}catch(e){console.error(e.stack||e);process.exitCode=1}
