import { createCanvas } from '@napi-rs/canvas'
import { NEEDS_YOU } from './core.mjs'
export const COLORS={blocked:'#dc3c3c',question:'#eb9628',waiting:'#eb9628',idle:'#cdb446',compacting:'#4682dc',working:'#3cb45a',ended:'#464646',empty:'#34343a'}
const BG='#18181b',FG='#ebebeb',DIM='#787882',ACCENT='#9682f5',PAD=6,BAND=5
const glyph=new Set(['blocked','question','waiting','idle','compacting'])
function font(size,bold=false){return `${bold?'600 ':''}${size}px -apple-system, BlinkMacSystemFont, "Helvetica Neue", Arial, sans-serif`}
function width(ctx,text,size=14){ctx.font=font(size);return ctx.measureText(String(text)).width}
function trunc(ctx,text,max,size=14){text=String(text||'');if(width(ctx,text,size)<=max)return text;while(text&&width(ctx,text+'…',size)>max)text=text.slice(0,-1);return text?text+'…':''}
function rounded(ctx,x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fill()}
export function titleOf(s){return ['workspace','agent'].includes(s.kind)?String(s.title||'?'):null}
export function subtitleOf(s){return s.kind==='agent'&&s.subtitle?String(s.subtitle):null}
export function overflow(s,size={width:80,height:80}){const c=createCanvas(1,1).getContext('2d'),max=size.width-12-(glyph.has(s.status)?16:0),t=titleOf(s);return t?[width(c,t)>max,width(c,t)]:[false,0]}
export function subtitleOverflow(s,size={width:80,height:80}){const c=createCanvas(1,1).getContext('2d'),t=subtitleOf(s);return t?[width(c,t,11)>size.width-12,width(c,t,11)]:[false,0]}
function centered(ctx,text,w,h,color=FG,size=15){ctx.fillStyle=color;ctx.font=font(size);ctx.textBaseline='alphabetic';ctx.fillText(text,(w-width(ctx,text,size))/2,h/2+3)}
function drawText(ctx,text,x,y,max,size,color,scroll=0,marquee=false){ctx.fillStyle=color;ctx.font=font(size);ctx.save();ctx.beginPath();ctx.rect(x,y-2,max,18);ctx.clip();if(marquee){const tw=width(ctx,text,size),period=tw+16,off=scroll%period;for(let px=x-off;px<x+max;px+=period)ctx.fillText(text,px,y+12)}else ctx.fillText(trunc(ctx,text,max,size),x,y+12);ctx.restore()}
function dots(ctx,s,y,w){const ds=s.dots||[];if(!ds.length){drawText(ctx,'no agents',PAD,y-4,w-12,11,DIM);return}let x=PAD;for(const state of ds.slice(0,4)){ctx.fillStyle=COLORS[state]||DIM;ctx.beginPath();ctx.arc(x+4,y+4,4,0,Math.PI*2);ctx.fill();x+=13}for(let i=0;i<(s.subagents||0)&&x<w-PAD;i++){ctx.fillStyle=ACCENT;ctx.beginPath();ctx.arc(x+2,y+4,2,0,Math.PI*2);ctx.fill();x+=8}}
function badge(ctx,label,w,h,color){ctx.font=font(11);const bw=ctx.measureText(label).width+10;ctx.fillStyle=color;ctx.beginPath();ctx.roundRect(w-PAD+2-bw,h-PAD-14,bw,15,7);ctx.fill();ctx.fillStyle=FG;ctx.fillText(label,w-PAD+7-bw,h-PAD-3)}
function statusGlyph(ctx,s,w){ctx.strokeStyle=FG;ctx.fillStyle=FG;ctx.lineWidth=2;const x=w-18,y=8;if(s==='question'){ctx.font=font(16,true);ctx.fillText('?',x+3,y+11)}else if(s==='waiting'){ctx.beginPath();ctx.moveTo(x,y+7);ctx.lineTo(x+5,y+12);ctx.lineTo(x+14,y+1);ctx.stroke()}else if(s==='idle'){for(let i=0;i<3;i++){ctx.beginPath();ctx.arc(x+2+i*5,y+10,1.5,0,Math.PI*2);ctx.fill()}}else if(s==='compacting'){for(const dy of [0,4]){ctx.beginPath();ctx.moveTo(x,y+dy+2);ctx.lineTo(x+7,y+dy+7);ctx.lineTo(x+14,y+dy+2);ctx.stroke()}}else if(s==='blocked'){ctx.strokeRect(x+1,y+7,12,8);ctx.beginPath();ctx.arc(x+7,y+7,5,Math.PI,0);ctx.stroke()}}
export function paintKey(spec,size={width:80,height:80},opts={}){const {width:w,height:h}=size,c=createCanvas(w,h),ctx=c.getContext('2d');ctx.fillStyle=spec.kind==='blank'?'#000':BG;ctx.fillRect(0,0,w,h);if(spec.kind==='blank')return c.data();if(spec.kind==='message'){centered(ctx,String(spec.text||''),w,h,DIM);return c.data()}if(spec.kind==='more'){centered(ctx,`▶ ${spec.remaining||0} more`,w,h);return c.data()}if(spec.kind==='back'){centered(ctx,'◀ back',w,h);if(spec.title)drawText(ctx,spec.title,PAD,h/2+5,w-12,11,DIM);return c.data()}
const state=spec.status||'idle';ctx.fillStyle=COLORS[state]||DIM;ctx.globalAlpha=opts.pulse??1;ctx.fillRect(0,0,w,BAND);ctx.globalAlpha=1;if(spec.selected){ctx.fillStyle=ACCENT;ctx.fillRect(0,BAND+1,3,h)}const title=String(spec.title||'?'),g=glyph.has(state)?16:0;drawText(ctx,title,PAD,PAD+2,w-12-g,14,FG,opts.scroll||0,opts.marquee);if(spec.kind==='workspace')dots(ctx,spec,PAD+24,w);else if(spec.subtitle)drawText(ctx,spec.subtitle,PAD,PAD+22,w-12,11,DIM,opts.subScroll||0,opts.subMarquee);if(spec.age)drawText(ctx,String(spec.age),PAD,h-20,w-12,10,DIM);if(spec.kind==='workspace'&&spec.count)badge(ctx,`${spec.count}π`,w,h,'#2c2c34');if(spec.kind==='agent'&&spec.subagents)badge(ctx,`⤷${spec.subagents}`,w,h,ACCENT);if(glyph.has(state))statusGlyph(ctx,state,w);return c.data()}
export { NEEDS_YOU }
